
package io.spring.guides.gs_producing_web_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EquationsPortService", targetNamespace = "http://spring.io/guides/gs-producing-web-service", wsdlLocation = "http://localhost:8080/ws/equations.wsdl")
public class EquationsPortService
    extends Service
{

    private final static URL EQUATIONSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EQUATIONSPORTSERVICE_EXCEPTION;
    private final static QName EQUATIONSPORTSERVICE_QNAME = new QName("http://spring.io/guides/gs-producing-web-service", "EquationsPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/equations.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EQUATIONSPORTSERVICE_WSDL_LOCATION = url;
        EQUATIONSPORTSERVICE_EXCEPTION = e;
    }

    public EquationsPortService() {
        super(__getWsdlLocation(), EQUATIONSPORTSERVICE_QNAME);
    }

    public EquationsPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EQUATIONSPORTSERVICE_QNAME, features);
    }

    public EquationsPortService(URL wsdlLocation) {
        super(wsdlLocation, EQUATIONSPORTSERVICE_QNAME);
    }

    public EquationsPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EQUATIONSPORTSERVICE_QNAME, features);
    }

    public EquationsPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EquationsPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EquationsPort
     */
    @WebEndpoint(name = "EquationsPortSoap11")
    public EquationsPort getEquationsPortSoap11() {
        return super.getPort(new QName("http://spring.io/guides/gs-producing-web-service", "EquationsPortSoap11"), EquationsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EquationsPort
     */
    @WebEndpoint(name = "EquationsPortSoap11")
    public EquationsPort getEquationsPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://spring.io/guides/gs-producing-web-service", "EquationsPortSoap11"), EquationsPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EQUATIONSPORTSERVICE_EXCEPTION!= null) {
            throw EQUATIONSPORTSERVICE_EXCEPTION;
        }
        return EQUATIONSPORTSERVICE_WSDL_LOCATION;
    }

}
